/*
 * JSP generated by Resin-3.0.21 (built Thu, 10 Aug 2006 12:03:19 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _login__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=iso-8859-1");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String error=request.getParameter("error");
if(error==null || error=="null"){
 error="";
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((error));
      out.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -6418134904411496499L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("login.jsp"), -1039478439977001830L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = "</div>\n\n\n\n\n<form name=\"frmLogin\" onSubmit=\"return validate();\" action=\"doLogin.jsp\" method=\"post\">\nUser Name <input type=\"text\" name=\"sUserName\" /><br />\nPassword <input type=\"password\" name=\"sPwd\" /><br />\n<input type=\"submit\" name=\"sSubmit\" value=\"Submit\" />\n</form>\n\n\n\n<FORM METHOD=\"LINK\" ACTION=\"newLogin.jsp\">\n<INPUT TYPE=\"SUBMIT\" VALUE=\"Register New User\">\n</FORM>\n\n\n</body>\n</html>".toCharArray();
    _jsp_string1 = "\n<html>\n<head>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet.css\" />\n<div id=\"header\"></div>\n\n\n<title>User Login JSP</title>\n<script>\n    function trim(s)\n    {\n        return s.replace( /^\\s*/, \"\" ).replace( /\\s*$/, \"\" );\n    }\n\n    function validate()\n    {\n        if(trim(document.frmLogin.sUserName.value)==\"\")\n        {\n          alert(\"Please Enter your ID Number/Username.\");\n          document.frmLogin.sUserName.focus();\n          return false;\n        }\n        else if(trim(document.frmLogin.sPwd.value)==\"\")\n        {\n          alert(\"Please Enter your password.\");\n          document.frmLogin.sPwd.focus();\n          return false;\n        }\n    }\n</script>\n</head>\n\n<body>\n<div>".toCharArray();
    _jsp_string0 = "\n\n\n".toCharArray();
  }
}
