/*
 * JSP generated by Resin-3.0.21 (built Thu, 10 Aug 2006 12:03:19 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _success__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=iso-8859-1");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       if (session.getAttribute("sUserID") == null)
{
   String redirectURL = "http://ac31004.computing.dundee.ac.uk:8080/jamesrichmond/login.jsp";
    response.sendRedirect(redirectURL);
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      

out.print("UserID:"+session.getAttribute("sUserID")+"<br>");
out.print("Username:"+session.getAttribute("sUserName"));


      out.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -6418134904411496499L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("success.jsp"), 7495356323814183047L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  static {
    _jsp_string0 = "\n\n\n\n\n<html>\n<head>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet.css\" />\n<div id=\"header\"></div>\n	\n<title>Successfully Logged in to Mr FaultY!</title>\n</head>\n\n<body>\n\n".toCharArray();
    _jsp_string1 = "\n\n\n".toCharArray();
    _jsp_string2 = "\n<br>\n\n<FORM>\n<INPUT TYPE=\"BUTTON\" VALUE=\"VIEW FAULT\" ONCLICK=\"window.location.href='http://ac31004.computing.dundee.ac.uk:8080/jamesrichmond/ViewFaults.jsp'\"> \n\n<br>\n<INPUT TYPE=\"BUTTON\" VALUE=\"REPORT FAULT\" ONCLICK=\"window.location.href='http://ac31004.computing.dundee.ac.uk:8080/jamesrichmond/ReportFault.jsp'\"> \n</FORM>\n\n\n\n\n</body>\n</html>".toCharArray();
  }
}
